"""Create tables

Revision ID: fc6132296b34
Revises:
Create Date: 2025-10-21 19:03:02.367829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6132296b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название доски.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи в таблице.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название группы.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи в таблице.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sprints',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название спринта.'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Дата начала спринта.'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Дата окончания спринта.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи в таблице.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='Имя и фамилия пользователя.'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='Электронная почта пользователя.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи в таблице.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи в таблице в формате RFC3339(YYYY-MM-DDTHH:mm:ssZ)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('columns',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название столбца.'),
    sa.Column('board_id', sa.Uuid(), nullable=False, comment='Внешний ключ с таблицей boards.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи в таблице.'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Название задачи.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание задачи.'),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='task_status'), server_default='TODO', nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False, comment='Внешний ключ с таблицей users. (Автор задачи)'),
    sa.Column('assignee_id', sa.Uuid(), nullable=True, comment='Внешний ключ с таблицей users. (Ответственный за выполнение задачи)'),
    sa.Column('column_id', sa.Uuid(), nullable=True, comment='Внешний ключ с таблицей columns.'),
    sa.Column('sprint_id', sa.Uuid(), nullable=True, comment='Внешний ключ с таблицей sprints.'),
    sa.Column('board_id', sa.Uuid(), nullable=True, comment='Внешний ключ с таблицей boards.'),
    sa.Column('group_id', sa.Uuid(), nullable=True, comment='Внешний ключ с таблицей groups.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи в таблице.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи в таблице в формате RFC3339(YYYY-MM-DDTHH:mm:ssZ)'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_author_id'), 'tasks', ['author_id'], unique=False)
    op.create_index(op.f('ix_tasks_board_id'), 'tasks', ['board_id'], unique=False)
    op.create_index(op.f('ix_tasks_column_id'), 'tasks', ['column_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_group_id'), 'tasks', ['group_id'], unique=False)
    op.create_index(op.f('ix_tasks_sprint_id'), 'tasks', ['sprint_id'], unique=False)
    op.create_table('task_executors',
    sa.Column('task_id', sa.Uuid(), nullable=False, comment='Внешний ключ с таблицей tasks.'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Внешний ключ с таблицей users.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи в таблице.'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='idx_unique_task_user_executor')
    )
    op.create_table('task_watchers',
    sa.Column('task_id', sa.Uuid(), nullable=False, comment='Внешний ключ с таблицей tasks.'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Внешний ключ с таблицей users.'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор записи в таблице.'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='idx_unique_task_user_watcher')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_watchers')
    op.drop_table('task_executors')
    op.drop_index(op.f('ix_tasks_sprint_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_group_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_column_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_board_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_author_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('columns')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('sprints')
    op.drop_table('groups')
    op.drop_table('boards')
    op.execute('DROP TYPE IF EXISTS task_status')
    # ### end Alembic commands ###
